
# GAME PARAMETERS
TIME_OF_SPECIAL_ABILITY = 5
MULTIPLICATION_DELAY = 10
TURTLE_REFLECTS_BELOW = 5
GUARANA_POWER_UP = 3
PLANTS_INITIATIVE = 0

# STARTUP PARAMETERS
POPULATION_PERCENTAGE = 0.17
NUMBER_OF_IMPLEMENTED_ORGANISMS = 11

# ORGANISMS PARAMETERS

# HUMAN PARAMETERS
HUMAN = 'H'
HUMAN_POWER = 5
HUMAN_INITIATIVE = 4

# WOLF PARAMETERS
WOLF = 'W'
WOLF_POWER = 9
WOLF_INITIATIVE = 5

# SHEEP PARAMETERS
SHEEP = 'S'
SHEEP_POWER = 4
SHEEP_INITIATIVE = 4

# FOX PARAMETERS
FOX = 'F'
FOX_POWER = 3
FOX_INITIATIVE = 7

# TURTLE PARAMETERS
TURTLE = 'T'
TURTLE_POWER = 2
TURTLE_INITIATIVE = 1

# ANTELOPE PARAMETERS
ANTELOPE = 'A'
ANTELOPE_POWER = 4
ANTELOPE_INITIATIVE = 4

# CYBER_SHEEP PARAMETERS
CYBER_SHEEP = 'C'
CYBER_SHEEP_POWER = 11
CYBER_SHEEP_INITIATIVE = 4

# GRASS PARAMETERS
GRASS = 'G'
GRASS_POWER = 0
GRASS_SPREAD_PROBABILITY = 0.1

# DANDELION PARAMETERS
DANDELION = 'D'
DANDELION_POWER = 0
DANDELION_SPREAD_PROBABILITY = 0.03

# GUARANA PARAMETERS
GUARANA = 'U'
GUARANA_POWER = 0
GUARANA_SPREAD_PROBABILITY = 0.06

# BELLADONNA PARAMETERS
BELLADONNA = 'B'
BELLADONNA_POWER = 99
BELLADONNA_SPREAD_PROBABILITY = 0.02

# SOSNOWSKYS HOGWEED PARAMETERS
SOSNOWSKYS_HOGWEED = 'P'
SOSNOWSKYS_HOGWEED_POWER = 10
SOSNOWSKYS_HOGWEED_SPREAD_PROBABILITY = 0.01
